version: "3"

services:
  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      PORT: "3000"
    volumes:
      - "./backend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    command: [ "npm", "run", "dev" ]
